### ISSUE TITLE
关于“括号”翻译问题的建议

### ISSUE THREAD

**Issue by callmewindow** [BUAA-SE-Compiling/miniplc0-handbook#10]
刚在找花括号的翻译的时候，偶然发现了三种括号的翻译（百度翻译搜索“括号”后汉英大词典上写的）：
大括号braces brace
方括号brackets bracket
圆括号parentheses parenthesis
考虑到以后实验的内容，感觉mini里的括号可以改成这个圆括号的翻译，为可能的方括号留有翻译的余地

**Comment by fazdzz** [comment]
感谢您的建议

这个问题最开始也讨论过，当时的方案一个是你说的这个，另一个是round bracket、square bracket和curly bracket。因为mini才一种括号就搁置了。

从给以后做打算的角度的确应该尽早整个方案出来。但是 mini PLC0 的定位当前只是一个过渡，我们也不太确定以后会变成什么样（像OJ那个语法分析题一样带个数组？完全变成 mini C0 ？）。可能需要以后的助教来论证了。

**Comment by callmewindow** [comment]
懂liao

**Comment by wtdcode** [comment]
0202力
