### ISSUE TITLE
莫名其妙通过了几个测试

### ISSUE THREAD

**Issue by st2r** [BUAA-SE-Compiling/miniplc0-handbook#13]
我在App.java中加了一段代码

![image](https://user-images.githubusercontent.com/36465934/97067604-ab4a3180-15f1-11eb-960d-6448b513c0ca.png)

让程序应该既不做词法分析也不做语法分析，为什么还是能通过一些测试点呢

![image](https://user-images.githubusercontent.com/36465934/97067649-16940380-15f2-11eb-9af3-62aeda23cb2c.png)

**Comment by wtdcode** [comment]
如果你们助教没有换样例，本来C++版原样交上去就能过好几个样例，即使这样去年还有0分呢。

________________________________

**Comment by lynzrand** [comment]
这是 feature，到 c0 的时候就不管用了（笑）

**Comment by fazdzz** [comment]
> 如果你们助教没有换样例，本来C++版原样交上去就能过好几个样例，即使这样去年还有0分呢。


震惊，编译器实验竟自带保底机制，我都不知道

**Comment by st2r** [comment]
原来是酱紫，助教们也太体贴了XD。

**Comment by lynzrand** [comment]
> 
> 
> > 如果你们助教没有换样例，本来C++版原样交上去就能过好几个样例，即使这样去年还有0分呢。
> 
> 震惊，编译器实验竟自带保底机制，我都不知道

其实是因为现在还做不到让某些测试点预期行为就是失败（躺）
