### ISSUE TITLE
添加使用 VSCode 远程开发的方式

### ISSUE THREAD

**Issue by ndsf** [BUAA-SE-Compiling/miniplc0-handbook#3]
在这里添加使用 Visual Studio Code 远程开发的方式，可以免去对 Docker 的配置进行修改。

> D.2.3 代码都在 container 里怎么上 IDE 呀
> 
> docker volume / mount 请自行探索。
> 
> 或者也可以先在本地写，提交前测试改好。
> 

https://code.visualstudio.com/docs/remote/containers

安装 Remote - Containers
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/32725248/68524147-268dd700-02fe-11ea-97e2-012b34349d51.png">
点左下角，选择 Attach to Running Container
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/32725248/68524156-4d4c0d80-02fe-11ea-81fb-52bda6867a01.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/32725248/68524159-59d06600-02fe-11ea-9dc1-3bef61abd0be.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/32725248/68524163-5f2db080-02fe-11ea-90eb-2618e944c367.png">

**Comment by wtdcode** [comment]
感谢参与实验设计。

我稍后会看一下，虽然不是勘误但是应该也算在加分。

**Comment by Zx55** [comment]
补充下vscode连接remote container前必须运行这个container

**Comment by Zx55** [comment]
补充下：
vscode连接remote container前必须运行这个container
```sh
docker run -td lazymio/compilers-env /bash/bin
```

![image](https://user-images.githubusercontent.com/37368558/68538080-b2107200-03a9-11ea-9820-6caae8789689.png)
这两个按钮连接过去会更方便一些

**Comment by wtdcode** [comment]
@ndsf @Zx55 两位同学本地系统和远程系统分别是什么？
指导书主要还是想照顾大多数用 windows 的同学，如果提 vsc remote 的话在 windows 上似乎并不是一件省心的事情，感觉需要一些动手能力。

**Comment by Zx55** [comment]
我的方案是win10装docker，vscode装remote - containers就可以用了
* win10 1903 
* Docker version 19.03.2, build 6a30dfc (windows)
* vscode 1.40.0
* remote - containers 0.83.0

我觉得除了配环境之外，还有一个比较大的问题就是cmake项目的调试
* vscode需要配置，我这边还没配上
    ~~有点懒不想配了 直接clion写然后扔remote - container里调试了~~
* vs不太清楚（看指导书是要装插件）
* clion是直接可以调试的

**Comment by wtdcode** [comment]
@Zx55 Docker on Windows 是不是需要 Hyper-V？

**Comment by Zx55** [comment]
> @Zx55 Docker on Windows 是不是需要 Hyper-V？

是的，我这里没开hyper-v的话docker是启动不了的，需要重启一下

**Comment by ndsf** [comment]
> @ndsf @Zx55 两位同学本地系统和远程系统分别是什么？
> 指导书主要还是想照顾大多数用 windows 的同学，如果提 vsc remote 的话在 windows 上似乎并不是一件省心的事情，感觉需要一些动手能力。

系统是 MacOS 10.15.1， Docker version 19.03.4, build 9013bf5，远程系统就是直接连接本机运行的 Docker，不是服务器。
主要的好处是不需要额外配置SSH，可以直接连上。
VSCode 是微软出的，在 Windows 上应该也可以直接用。

**Comment by wtdcode** [comment]
@Zx55 那首先我的笔记本 Windows10 Home 就启动不了.jpg

那可能还是开虚拟机（VBox/VMWare）然后通过 ssh 普适一些，但是这样会引入新的问题就是虚拟机网卡配置，指导书的目标不是写完备的教程，但是这的确有利于降低实验门槛，不知道能不能寄希望于 WSL2 的成熟。

总之我的想法是这个东西很好，但似乎不太适合写到指导书，然而还没想法应该写到哪。

@ndsf 我有 mac 环境我知道方便的多，然而 Windows 上还有些繁琐。

**Comment by wtdcode** [comment]
目前暂时加了一个从指导书到这里的链接。

**Comment by wtdcode** [comment]
添加了说明，见[这里](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/commit/d5d52e9bcb0cbea7ad536675d3015fb58c2dae22)，任何同学有问题的话再回复吧。

@Zx55 @ndsf 麻烦按照格式发送邮件记录一下。

感谢参与实验设计。
