### ISSUE TITLE
对于指导书中状态图 无符号整数 和 标识符 的终态的疑问

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/miniplc0-handbook#5]
指导书中给出的状态图是
![mini-plc0 词法分析状态图](https://i.imgur.com/8EWWERh.png)

以EOF作为无符号整数和标识符的终态是不是有点奇怪？
（读一个无符号整数到最后变成了EOF状态？

结合[miniplc0-compiler #1](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/issues/1)我画出的的状态图是
![image](https://user-images.githubusercontent.com/37368558/68538769-ae361d00-03b4-11ea-963f-bf76b12daeee.png)

**Comment by wtdcode** [comment]
Possible duplicate of #4

**Comment by Zx55** [comment]
主要的疑问在于 图中使用EOF作为终态是否描述的不太清晰
可能意思是无符号整数直到遇到EOF就不再就收输入了
但是EOF不应该作为无符号整数的终态 图中是否改为无符号整数更好

并且这里遇到非数字非字母（123abc的情况）外就应该终止了 
而不用强调遇到EOF的情况
所以无符号整数除了接受数字和字母以外就没有其他的连线了

**Comment by fazdzz** [comment]
> 但是EOF不应该作为无符号整数的终态 图中是否改为无符号整数更好

我本地备份的图和这个长得不太一样，是正确的写了标识符和无符号整数的。。。可能出了点意料外的问题
如下：
![image](https://user-images.githubusercontent.com/22709633/68539742-0bd16600-03c3-11ea-92a9-69d877739dc4.png)

> 并且这里遇到非数字非字母（123abc的情况）外就应该终止了
> 而不用强调遇到EOF的情况
> 所以无符号整数除了接受数字和字母以外就没有其他的连线了

这个问题在[miniplc0-compiler #1](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/issues/1)也有人提出了，请关注。

**Comment by fazdzz** [comment]
感谢您对实验改正做出的贡献，已经在master分支提交了[修改](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/commit/8174750ab40eba35ed63c68bd6f0ae9484268e3a)。

也麻烦您之后通过邮箱发送本次勘误以便我们统计。
