### ISSUE TITLE
关于测试方式的疑问

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/miniplc0-handbook#7]
最终在OJ上比较的是miniplc0编译出来代码跑的结果吗？
还是输出的指令序列吗？因为涉及到指令集的生成问题

**Comment by wtdcode** [comment]
[这里](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/tree/69f1a334c6ef9c4d11fce0ddd8d13e77ef07b07c#384-%E6%88%91%E4%BB%AC%E6%80%8E%E4%B9%88%E8%AF%84%E6%B5%8B%E4%BB%A3%E7%A0%81)

> 我们会用一个特殊的脚本把整个项目变形为 OJ 可接受的源码，然后**补全输入输出调用源码中的 Tokenizer 和 Analyser 分析输入**提交到 OJ 上自动化跑样例，有点类似 Special Judge。

**Comment by wtdcode** [comment]
哦，好像误解了你的意思，依赖的是程序的结果。

也就是说比如 

```
begin
    var a=0;
    a = 2*5;
    print(a);
end
```

你直接

```
LIT 10
WRT
```

完全没问题

**Comment by Zx55** [comment]
好的

**Comment by wtdcode** [comment]
[添加了说明](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/commit/5f0ae9231235c9fd56ece759305ea9ab54d9532c)

感谢参与实验设计，不过这个不算勘误哈。
